// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Pagina principal",
};
import Nabvar from "@/components/Nabvar";
import Link from "next/link";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
    >
      <Nabvar />
        {children}
      </body>
    </html>
  );
}
